Arithmetic

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2,1],[2,2,3]])
B = np.array([3,4,5])

In [4]:
#Soma
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [5]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

In [6]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [7]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

Conditional

In [8]:
x = np.array([i for i in range(10)])

In [9]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.where(x%2==0, 'Even', 'Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [11]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [12]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

Math Functions

In [14]:
arrayfunc = np.array([[4,3,2],[10,1,0],[5,8,24]])
arrayfunc

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [16]:
#metodo amin para achar valor minimo do array
np.amin(arrayfunc)

0

In [18]:
#tambem é possivel ver valores minimos informando o axis -> 0 = vertical 1 = horizontal
np.amin(arrayfunc,axis=0)

array([4, 1, 0])

In [19]:
np.amin(arrayfunc,axis=1)

array([2, 0, 5])

In [20]:
#valor maximo de uma array
np.max(arrayfunc) #tambem pode ser adicionado o axis aqui

24

In [21]:
np.median(arrayfunc) #media

4.0

In [22]:
np.mean(arrayfunc) #mediana

6.333333333333333

In [24]:
np.percentile(arrayfunc,26) #define a % de toda a array

2.08

In [26]:
#criando uma array de degrees para calcular o seno
degres = np.array([0,30,45,60,90])

In [27]:
np.sin(degres*np.pi/180) #calc do seno

array([0.        , 0.80901699, 0.98768834, 0.95105652, 0.30901699])

In [28]:
np.cos(degres*np.pi/180) #coseno

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [ ]:
np.tan(degres*np.pi/180) #tangente