In [1]:
import numpy as np

In [2]:
np.array(24)

array(24)

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
#2d array
np.array([[1,1,1],[1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

In [6]:
#3d array
np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [7]:
numpy_array = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [9]:
numpy_array.shape

(2, 2, 3)

In [10]:
#dimensions
numpy_array.ndim

3

Criando uma array e convertendo

In [12]:
numpy_second_array = np.array([x for x in range (1,10)])
numpy_second_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#reshape in 2d
numpy_second_array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#new array to reshape in 3d
numpy_t_arr = np.array([x for x in range(1,13)])
numpy_t_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
numpy_t_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
numpy_t_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [18]:
#calc auto the third dimension 
numpy_t_arr.reshape(2,2,-1) #use -1 

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

3d Array to flat Array

In [20]:
#Creating 3d array
numpy_t_arr = numpy_t_arr.reshape(3,2,2)

In [21]:
numpy_t_arr.reshape(-1) #use -1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])