Indexing

In [1]:
import numpy as np

In [11]:
array1d = np.array([1,2,3,4])
array2d = np.array([[1,2,3,4],[1,2,3,4]])
array3d = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,5]]])


In [8]:
array1d[0]

1

In [9]:
array2d[0,1]

2

In [13]:
array3d[0,0,1]

2

Slicing

In [16]:
array1d[1:]

array([2, 3, 4])

In [19]:
array1d[1:2]

array([2])

In [20]:
array2d[1,1:]

array([2, 3, 4])

In [22]:
array2d[-2:-3:-1]

array([[1, 2, 3, 4]])

In [23]:
array3d[1,1,1:]

array([2, 5])