In [11]:
#import Numpy library
import numpy as np

In [12]:
#first Numpy array
numpy_array = np.array([1,2,3,4])

In [15]:
print (numpy_array)

[1 2 3 4]


In [16]:
#array with zeros
array_zeros = np.zeros((3,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#array with ones
array_ones = np.ones((3,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#empty array
empty_array = np.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#array with arange method
np_arange = np.arange(12)
print (np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
#reshape method to change/create array -> on previous array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
#linspace for linearly (equal) space data elements
np_linspce = np.linspace(1,6,5)
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [31]:
#1D array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [34]:
#2D array
twoD_array = oneD_array.reshape(3,5)
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [37]:
#3D array
threeD_array = np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
