# Importando NumPy

In [ ]:
#importando toda library
import math
#importando com um prefixo 
import math as mt
#importando somente um metodo 
from math import sqrt, sin

In [1]:
#testanto
from math import sqrt, sin
a = 16
b = 3.14
print(sqrt(a))
print(sin(b))

4.0
0.0015926529164868282


# NumPy

In [2]:
import numpy as np

In [4]:
#sqrt dá a raiz quadrada
np_sqrt = np.sqrt ([4,16,64])
np_sqrt

array([2., 4., 8.])

In [9]:
#cos define o coseno
np.cos(0)

1.0

In [10]:
#sin define o seno
from numpy import pi #importando pi 
np.sin(pi/4)

0.7071067811865476

In [11]:
#Exp devolve exponencial de cada elemento
np.floor([1.3,2.5,1,5])

array([1., 2., 1., 5.])

In [12]:
#Floor devolve maior valor inteiro do array
np.exp([1,2,5])

array([  2.71828183,   7.3890561 , 148.4131591 ])

Shape Manipulation

In [14]:
#criando a array
exemplo = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

In [15]:
#Flattens
exemplo.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [21]:
#Reshape em linhas por colunas -> 3 Linhas e 4 Colunas
exemplo.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [24]:
#Resize dá de volta o tamanho original -> 2 por 6
exemplo.resize(2,6)
exemplo

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [48]:
#Stack juntam duas arrays
exemplo1 = np.array([10,15,17,26,13,19])
exemplo2 = np.array([12,11,21,24,14,23])
np.hstack((exemplo1,exemplo2))

TypeError: 'tuple' object is not callable

In [47]:
#Split separa a array em x
np.hsplit(exemplo,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]